// <auto-generated />
using FAQ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAQ.Migrations
{
    [DbContext(typeof(FAQContext))]
    [Migration("20251113195720_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FAQ.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "1",
                            Name = "General"
                        },
                        new
                        {
                            CategoryId = "2",
                            Name = "History"
                        },
                        new
                        {
                            CategoryId = "3",
                            Name = "Troubleshooting"
                        },
                        new
                        {
                            CategoryId = "4",
                            Name = "Bugs"
                        },
                        new
                        {
                            CategoryId = "5",
                            Name = "Domain Modeling"
                        },
                        new
                        {
                            CategoryId = "6",
                            Name = "Annotations"
                        },
                        new
                        {
                            CategoryId = "7",
                            Name = "Misc"
                        },
                        new
                        {
                            CategoryId = "8",
                            Name = "Archive"
                        });
                });

            modelBuilder.Entity("FAQ.Models.FAQ", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Answer = "A CSS framework for creating responsive web apps for multiple screen sizes.",
                            CategoryId = "1",
                            Question = "What is Bootstrap?",
                            TopicId = "1"
                        },
                        new
                        {
                            Id = "2",
                            Answer = "A general purpose object oriented langauge that uses a concise, Java-like syntax.",
                            CategoryId = "2",
                            Question = "What is C#",
                            TopicId = "2"
                        },
                        new
                        {
                            Id = "3",
                            Answer = "A general purpose scripting langauge that executes in a web browser?",
                            CategoryId = "3",
                            Question = "What is JavaScript",
                            TopicId = "3"
                        },
                        new
                        {
                            Id = "4",
                            Answer = "In 2011",
                            CategoryId = "4",
                            Question = "When was Bootstrap first released?",
                            TopicId = "4"
                        },
                        new
                        {
                            Id = "5",
                            Answer = "C#",
                            CategoryId = "5",
                            Question = "When was C# first released",
                            TopicId = "5"
                        },
                        new
                        {
                            Id = "6",
                            Answer = "In 2011",
                            CategoryId = "6",
                            Question = "When was Bootstrap first released",
                            TopicId = "6"
                        },
                        new
                        {
                            Id = "7",
                            Answer = "In 2002",
                            CategoryId = "7",
                            Question = "When was C# first released?",
                            TopicId = "7"
                        },
                        new
                        {
                            Id = "8",
                            Answer = "In 1995",
                            CategoryId = "8",
                            Question = "When was JavaScript first released?",
                            TopicId = "8"
                        });
                });

            modelBuilder.Entity("FAQ.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = "1",
                            Name = "C#"
                        },
                        new
                        {
                            TopicId = "2",
                            Name = "JavaScript"
                        },
                        new
                        {
                            TopicId = "3",
                            Name = "Bootstrap"
                        },
                        new
                        {
                            TopicId = "4",
                            Name = "ASP.Net"
                        },
                        new
                        {
                            TopicId = "5",
                            Name = "Kotlin"
                        },
                        new
                        {
                            TopicId = "6",
                            Name = "SQL"
                        },
                        new
                        {
                            TopicId = "7",
                            Name = "PL/SQL"
                        },
                        new
                        {
                            TopicId = "8",
                            Name = "Java"
                        });
                });

            modelBuilder.Entity("FAQ.Models.FAQ", b =>
                {
                    b.HasOne("FAQ.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAQ.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
