using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace ContactManager.Models
{
    public class Contact
    {
        // primary key - generated by database
        public int ContactId { get; set; }         

        [Required(ErrorMessage = "Please enter a first name.")]
        public string Firstname { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a last name.")]
        public string Lastname { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a phone number.")]
        public string Phone { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter an email.")]
        public string Email { get; set; } = string.Empty;

        // no validation bc will be set by application, not user
        public DateTime DateAdded { get; set; }   

        // foreign key
        [Range(1, 100000000, ErrorMessage = "Please select a category.")] // make sure value is greater than zero
        public int CategoryId { get; set; }
        [ValidateNever]  // suppress unwanted validation of navigation property
        public Category Category { get; set; } = null!;

        // read-only property
        public string Slug => Firstname?.Replace(' ', '-').ToLower() 
            + '-' + Lastname?.Replace(' ', '-').ToLower();
    }
}